### ISSUE TITLE
Support Node 18

### ISSUE THREAD

**Issue by boris-moduscreate** [toolsplus/atlassian-marketplace-sheets-connector#1]
Fails with:

```

node:internal/crypto/hash:71
  this[kHandle] = new _Hash(algorithm, xofLen);
                  ^

Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:71:19)
    at Object.createHash (node:crypto:133:10)
    at BulkUpdateDecorator.hashFactory (/Users/boris/repo/atlassian-marketplace-sheets-connector/node_modules/webpack/lib/util/createHash.js:145:18)
    at BulkUpdateDecorator.digest (/Users/boris/repo/atlassian-marketplace-sheets-connector/node_modules/webpack/lib/util/createHash.js:80:21)
    at NormalModule._initBuildHash (/Users/boris/repo/atlassian-marketplace-sheets-connector/node_modules/webpack/lib/NormalModule.js:892:53)
    at /Users/boris/repo/atlassian-marketplace-sheets-connector/node_modules/webpack/lib/NormalModule.js:932:10
    at processResult (/Users/boris/repo/atlassian-marketplace-sheets-connector/node_modules/webpack/lib/NormalModule.js:728:12)
    at /Users/boris/repo/atlassian-marketplace-sheets-connector/node_modules/webpack/lib/NormalModule.js:827:5
    at /Users/boris/repo/atlassian-marketplace-sheets-connector/node_modules/loader-runner/lib/LoaderRunner.js:399:11
    at /Users/boris/repo/atlassian-marketplace-sheets-connector/node_modules/loader-runner/lib/LoaderRunner.js:251:18 {
  opensslErrorStack: [ 'error:03000086:digital envelope routines::initialization error' ],
  library: 'digital envelope routines',
  reason: 'unsupported',
  code: 'ERR_OSSL_EVP_UNSUPPORTED'
}
```

**Comment by tbinna** [comment]
This should be fixed in the latest commit. 

Sorry, this repo lacks a proper CI build and automated dependency updates. Those are probably the next things that should be fixed.
